name: QuartoDocs
on:
  pull_request:
    branches: develop

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Quarto
              uses: quarto-dev/quarto-actions/setup@v2

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.10"
                cache: "pip"

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install -e ".[docs]"

            - name: Build API reference
              run: |
                cd docs
                python -m quartodoc build

            - name: Publish to gh-pages
              uses: quarto-dev/quarto-actions/publish@v2
              with:
                target: gh-pages
                render: true
                path: docs
